<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "{{%product_model_attr}}".
 *
 * @property integer $product_model_attr_id
 * @property integer $model_id
 * @property integer $model_attr_id
 * @property integer $product_id
 * @property string $attr_value
 * @property integer model_attr_value_id
 */
class ProductModelAttr extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%product_model_attr}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['model_id', 'model_attr_id', 'product_id','model_attr_value_id'], 'integer'],
        	['model_id', 'exist', 'targetClass' => CategoryModel::className(), 'targetAttribute' => 'model_id'],
        	['model_attr_id', 'exist', 'targetClass' => CategoryModelAttr::className(), 'targetAttribute' => 'model_attr_id'],
        	['product_id', 'exist', 'targetClass' => Product::className(), 'targetAttribute' => 'product_id'],
        	['model_attr_value_id', 'exist', 'targetClass' => CategoryModelAttrValue::className(), 'targetAttribute' => 'model_attr_value_id'],
            [['attr_value'], 'string', 'max' => 45],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'product_model_attr_id' => Yii::t('common', 'Product Model Attr ID'),
            'model_id' => Yii::t('common', 'Model ID'),
            'model_attr_id' => Yii::t('common', 'Model Attr ID'),
            'product_id' => Yii::t('common', 'Product ID'),
            'attr_value' => Yii::t('common', 'Attr Value'),
        ];
    }
    
    public function beforeSave($insert) {
    	$value = CategoryModelAttrValue::findOne(['model_attr_value_id'=>$this->model_attr_value_id]);
    	$this->attr_value = $value->value_str;
    	return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    
    
	public function getCategoryModelAttr()
    {
        return $this->hasOne(CategoryModelAttr::className(), ['model_attr_id' => 'model_attr_id']);
    }
}
