<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create' => '创建',
    'Update' => '更新',
    'Create {modelClass}' => '创建{modelClass}',
    'Update {modelClass}: ' => '更新{modelClass}:',
    'Carousel' => '幻灯片',
    'Nav' => '导航',
    'Navs' => '导航',
    'Account details' => '账户',
    'Profile details' => '信息',
    'Assignments' => '指派',
    'Block' => '封禁',
    'UnBlock' => '解禁',
    'Level' => '级别',
    'Category' => '分类',
    'Orders'=>'订单列表',
    'Address'=>'地址管理',
    'Create Order'=>'新增订单',
    'Create Address'=>'新增地址',
	'Account Logs'=>'账单记录',
    'Action User'=>'操作人',
    'Order Status'=>'订单状态',
    'Username'=>'用户名',
    'Mobile'=>'手机号码',
    'Relivery'=>'发货单',
    'Order Logs'=>'订单日志',
    'Action Note'=>'操作日志',
    'Create Time'=>'生成时间',
    'Status Desc'=>'状态描述',
    'Order ID'=>'订单id',
    'Send'=>'发货',
    'Shipping Companies'=>'物流公司',
    'Company Name'=>'公司名称',
    'Sort'=>'排序',
    'Refund'=>'退款',
    'Recharges'=>'充值纪录',
    'Create Recharge'=>'创建纪录',
    'Withdrawals'=>'提现纪录',
    'Create Withdrawal'=>'创建提现纪录',
     'Search'=>'搜索',
     'Reset'=>'取消',
     'Services'=>'售后服务',
     'Created At'=>'创建时间',
      'Comment'=>'备注',
     'order_no'=>'订单编号',
     'Money'=>'余额',
     'type'=>'类型',
     'Picks'=>'自提点管理',
    'Create Pick'=>'新建自提点',
    'Status'=>'状态',
    
    'You can assign multiple roles or permissions to user by using the form below' => '您可以使用下面的表单给用户分配多个角色或权限'
];